### ISSUE TITLE
Setting scheduledChar or deadlineChar to NA results in not being able to use the other.

### ISSUE THREAD

**Issue by W-Floyd** [benjypng/logseq-datenlp-plugin#57]
Looks like it's checking here: https://github.com/benjypng/logseq-datenlp-plugin/blob/c9d2c9efc2a46ddb8c07d76fcc6b6ce4a82ea77f/src/features/parse/semi-auto.ts#L45

which then (incorrectly) makes no change if either is NA.

**Comment by benjypng** [comment]
Fixed in the latest version.
