### ISSUE TITLE
`/` right after a word won't trigger the popup in Logseq 

### ISSUE THREAD

**Issue by aifreedom** [benjypng/logseq-datenlp-plugin#58]
It seems that now adding a `/` right after a word won't trigger the popup in Logseq. There has to be a space before the slash. But if the date NLP commands are not executed right after a word, they don't work. 

Can we strip the spaces and make them parse the last word before where the command is executed to make it more robust?

Thanks!

**Comment by benjypng** [comment]
I am unable to replicate this. Can you share the specific scenario and command you tried?

**Comment by aifreedom** [comment]
Here's screen recording. I've turned off all other plugins and themes.

https://github.com/benjypng/logseq-datenlp-plugin/assets/70373/c9deb221-172f-4bbf-a9d0-003823805a14

**Comment by benjypng** [comment]
Fixed in latest version.
