### ISSUE TITLE
Blocks with inline code don't parse the date

### ISSUE THREAD

**Issue by kaelhuerta** [benjypng/logseq-datenlp-plugin#59]
These two lines yield different results:
```
This is a test schedule for %tomorrow
This is a `test` schedule for %tomorrow
```

Only the first one parses the date correctly.

Here's the output:
![image](https://github.com/benjypng/logseq-datenlp-plugin/assets/6402208/5d2dbc78-b50e-4292-8eb2-19997bea4d34)

Thanks for such a helpful plugin!

**Comment by benjypng** [comment]
Fixed in latest version.
